### ISSUE TITLE
scATAC-seq time course experiment

### ISSUE THREAD

**Issue by jk86754** [aertslab/cisTopic#28]
Hi,

I have an experiment with four different time points using ATAC seq where the samples at the four time points come from different subjects. All the subject were treated the same at baseline and some of the subjects were used for sample collection at three different time points. So i have a total of four time points including the baseline samples. I analyzed the four time points separately and created separate cisTopic objects

My question is: can the four predMatSumByGene matrices generated in this process per the PBMC tutorials be 'combined' to get an estimation on gene accessibility changes over time? Or would you recommend a different method?

Thank you!

**Comment by cbravo93** [comment]
Hi @jk86754!

I have never tried something like that (normally we check per time point and also run a combined model; so we would use the combined model for this question), but it could work. The most critical step is how to link the regions to genes (e.g. you can aggregate regions in a certain space around the TSS + introns). 

Once you have your gene-based matrix, scRNA-seq oriented methods have worked quite well in our cases (e.g. Seurat, SCENIC; in your case maybe Monocle is interesting). If you see batch effects (though it may be hard to distinguish whether it is because of the time point or the runs), you can have a try with [harmony](https://github.com/immunogenomics/harmony); otherwise, getting the gene-based matrix on a combined model can help.

Hope this helps!

C

**Comment by jk86754** [comment]
Thank you. I had very similar ideas; it is good to get confirmation.
