### ISSUE TITLE
Plotting cluster info signaturesHeatmap

### ISSUE THREAD

**Issue by ccruizm** [aertslab/cisTopic#37]
Hello @cbravo93 !

I have got new insights on my dataset using cisTopic! Great package. This time I would like to know whether is possible to use `signaturesHeatmap` to display the cluster-info (e.g. 'densityClust') similar to `cellTopicHeatmap` 

Thanks in advance!

**Comment by cbravo93** [comment]
Hi @ccruizm !

This is currently not implemented, because we do not store topic or signature metadata in the cisTopicObject (only for regions and cells). However, you can use the newly added topicSignaturesMatrix() function to extract the enrichment matrix and customize your heatmap.

I hope this is useful!

C
