### ISSUE TITLE
subset a list of cells

### ISSUE THREAD

**Issue by hejing3283** [aertslab/cisTopic#52]
Hi I am new to cisTopic, Is there anyway to subset a list of cells?

**Comment by cbravo93** [comment]
Hi @hejing3283 !

There is not currently a straight way, because it is necessary to have all cells used to inferred the models in the cisTopicObject for some calculations. However, you can extract the counts matrix and metadata of a existing cisTopicObject and create a new object with those cells:

```r
cells <- 'Your vector with cells'
subset_counts <- cisTopicObject@count.matrix[,cells]
subset_metadata <- cisTopicObject@cell.data[cells,]
subset_cisTopicObject <- createcisTopicObject(subset_counts)
subset_cisTopicObject <- AddCellMetadata(subset_cisTopicObject, subset_metadata)
```

If you want to subset cells and use topics inferred in the entire population anyways, you can extract the topic cell matrix and subset your cells there:

```r
modelMat <- modelMatSelection(cisTopicObject, 'cell', 'Probability') 
modelMat_subset <- modelMat_subset[,cells]
```

Hope this helps!

C
